{
 "title": "dommu",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Consumi totali",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "total_active_energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "common" }
     ]
    }
   ]
  },
  {
   "title": "Consumi ultimo mese",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "SELECT (last(\"total_active_energy\") - first(\"total_active_energy\")) FROM \"energy\" WHERE (\"location\" = 'common') AND time >= now() - 30d and time <= now() ",
     "select": [
      [
       { "params": [ "total_active_energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "common" }
     ]
    }
   ]
  },
  {
   "title": "Consumi intervallo",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "total_active_energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "common" }
     ]
    }
   ]
  },
  {
   "title": "Consumi ultima ora",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "SELECT (last(\"total_active_energy\") - first(\"total_active_energy\")) FROM \"energy\" WHERE (\"location\" = 'common') AND time >= now() - 1h and time <= now() ",
     "select": [
      [
       { "params": [ "total_active_energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "common" }
     ]
    }
   ]
  },
  {
   "title": "Consumi ultimo giorno",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "SELECT (last(\"total_active_energy\") - first(\"total_active_energy\")) FROM \"energy\" WHERE (\"location\" = 'common') AND time >= now() - 1d and time <= now() ",
     "select": [
      [
       { "params": [ "total_active_energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "common" }
     ]
    }
   ]
  },
  {
   "title": "Consumi ultima settimana",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "SELECT (last(\"total_active_energy\") - first(\"total_active_energy\")) FROM \"energy\" WHERE (\"location\" = 'common') AND time >= now() - 7d and time <= now() ",
     "select": [
      [
       { "params": [ "total_active_energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "common" }
     ]
    }
   ]
  },
  {
   "title": "Potenza istantanea",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "active power",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "active_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "common" }
     ]
    },
    {
     "alias": "reactive power",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "reactive_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "common" }
     ]
    }
   ]
  },
  {
   "title": "Tensione",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "common" }
     ]
    }
   ]
  },
  {
   "title": "Corrente",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "common" }
     ]
    }
   ]
  },
  {
   "title": "Frequenza",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "frequency",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "freq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "common" }
     ]
    }
   ]
  },
  {
   "title": "Fattore di potenza",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "power factor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "common" }
     ]
    }
   ]
  }
 ]
}